#!/usr/bin/env bash
set -euo pipefail

seed_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
tmp_dir="$(mktemp -d)"
tmp_generated=""
cleanup() {
  rm -rf "$tmp_dir"
  if [ -n "$tmp_generated" ]; then
    rm -rf "$tmp_generated"
  fi
}
trap cleanup EXIT

cue vet \
  "$seed_root/contract/registry.cue" \
  "$seed_root/contract/projection.cue" \
  "$seed_root/contract/fragments.cue" \
  "$seed_root/contract/hooks.cue" \
  "$seed_root/contract/prompt_classifier.cue" \
  "$seed_root/contract/proof.cue" \
  "$seed_root/fixtures/registry.valid.cue"

"$seed_root/scripts/generate.sh" "$tmp_dir"
diff -ru "$seed_root/generated" "$tmp_dir"

go run "$seed_root/cmd/seed-resolver/main.go" validate \
  --generated "$seed_root/generated" \
  --valid-fixture "$seed_root/fixtures/prompt_classification.valid.cue"

tmp_generated="$(mktemp -d)"
cp "$seed_root/generated/"*.json "$tmp_generated/"
jq '.routes[0].selects += ["stale.fragment"]' \
  "$tmp_generated/prompt_routes.json" >"$tmp_generated/prompt_routes.json.tmp"
mv "$tmp_generated/prompt_routes.json.tmp" "$tmp_generated/prompt_routes.json"

if output="$(go run "$seed_root/cmd/seed-resolver/main.go" validate \
  --generated "$tmp_generated" \
  --valid-fixture "$seed_root/fixtures/prompt_classification.valid.cue" 2>&1)"; then
  echo "expected invalid prompt route declaration to fail" >&2
  exit 1
fi
if [[ "$output" != *'route "resolver": selected fragment "stale.fragment" was not generated by turnStart'* ]]; then
  echo "unexpected validation failure for stale prompt route: $output" >&2
  exit 1
fi

for fixture in "$seed_root"/fixtures/*.invalid.cue; do
  case "$(basename "$fixture")" in
    context_body_from_prompt.invalid.cue)
      expected="cannot assemble context bodies"
      ;;
    full_registry_from_prompt.invalid.cue)
      expected="cannot emit the registry"
      ;;
    mcp_tool_output_as_context.invalid.cue)
      expected="MCP/tool output cannot become implied context"
      ;;
    unknown_fragment.invalid.cue)
      expected="was not generated by turnStart"
      ;;
    *)
      echo "missing expected failure for fixture: $fixture" >&2
      exit 1
      ;;
  esac

  if output="$(go run "$seed_root/cmd/seed-resolver/main.go" validate-fixture \
    --generated "$seed_root/generated" \
    --fixture "$fixture" 2>&1)"; then
    echo "expected invalid fixture to fail: $fixture" >&2
    exit 1
  fi
  if [[ "$output" != *"$expected"* ]]; then
    echo "unexpected validation failure for $fixture: $output" >&2
    exit 1
  fi
done
