package epistemicplantprofile

publicContract: close({
	apiVersion: "factory.upstream-monitor.epistemic-plant-bootstrap/v2"
	kind: "EpistemicPlantBootstrapMultiSourceUpstreamMonitor"
	operational: bool
	signal: _
	authority: _
	context: _
	sources: _
	sourcePolicy: _
	actuator: _
	workflow: _
	controlInvariants: _
	surfaces: [...#EpistemicPlantSurface]
	classification: _
	graphNodes: _
	graphEdges: _
	testBindings: _
	probeBindings: _
	executionGraph: _
	correlation: _
	evidenceModel: _
	reportTemplate: _
	summaryTemplate: _
	publicationPlan: _
	publicationAdmission: _
	forbiddenAttractors: [...string]
	validationAssertions: _
	validationPlan: _
}) & {
	apiVersion: "factory.upstream-monitor.epistemic-plant-bootstrap/v2"
	kind: "EpistemicPlantBootstrapMultiSourceUpstreamMonitor"
	operational: epistemicPlantOperational
	signal: epistemicPlantAcceptedSignal
	authority: epistemicPlantAuthorityModel
	context: epistemicPlantContext
	sources: epistemicPlantSources
	sourcePolicy: epistemicPlantSourcePolicy
	actuator: chatgptActuator
	workflow: epistemicPlantWorkflow
	controlInvariants: epistemicPlantControlInvariants
	surfaces: epistemicPlantSurfaceCatalogue
	classification: epistemicPlantClassificationPolicy
	graphNodes: epistemicPlantGraphNodes
	graphEdges: epistemicPlantGraphEdges
	testBindings: epistemicPlantTestBindings
	probeBindings: epistemicPlantProbeBindings
	executionGraph: epistemicPlantExecutionGraphContract
	correlation: epistemicPlantCorrelationContract
	evidenceModel: epistemicPlantEvidenceModel
	reportTemplate: epistemicPlantImpactReportTemplate
	summaryTemplate: epistemicPlantRunSummaryTemplate
	publicationPlan: epistemicPlantPublicationPlan
	publicationAdmission: epistemicPlantPublicationAdmission
	forbiddenAttractors: epistemicPlantForbiddenAttractors
	validationAssertions: epistemicPlantValidationAssertions
	validationPlan: epistemicPlantValidationPlan
}
