package inf1120a26

conceptsFoundationLanguage: [
    {id: "concept:program-ipo", label: "Programme comme entrée → traitement → sortie", kind: "foundation", description: "Un programme reçoit des entrées, effectue un traitement et produit des sorties.", evidence: ["src:introduction"]},
    {id: "concept:programming-languages", label: "Niveaux de langages de programmation", kind: "foundation", description: "Langage machine, assembleur et langages de haut niveau; Java est présenté comme portable via sa chaîne d’exécution.", evidence: ["src:introduction"]},
    {id: "concept:java-execution-jvm", label: "Compilation et exécution Java / JVM", kind: "foundation", description: "Chaîne de compilation et exécution Java au moyen de la machine virtuelle Java.", evidence: ["src:introduction", "src:intro-java"]},
    {id: "concept:software-lifecycle", label: "Cycle de vie du logiciel", kind: "foundation", description: "Le cours situe spécification, conception, implémentation et vérification dans un cycle de vie simplifié.", evidence: ["src:introduction", "src:spec-conception"]},
    {id: "concept:problem-definition", label: "Définition du problème", kind: "specification", description: "Formuler le problème avant l’implémentation.", evidence: ["src:spec-conception"]},
    {id: "concept:functional-requirements", label: "Exigences fonctionnelles", kind: "specification", description: "Énumérer ce que le programme doit demander, calculer, valider et afficher.", evidence: ["src:spec-conception"]},
    {id: "concept:inputs-outputs", label: "Entrées et sorties", kind: "specification", description: "Identifier explicitement les données d’entrée et de sortie.", evidence: ["src:spec-conception"]},
    {id: "concept:data-types-model", label: "Types de données — modèle de conception", kind: "specification", description: "Associer catégories de données, opérations permises et domaines de valeurs.", evidence: ["src:spec-conception"]},
    {id: "concept:boolean-logic", label: "Logique booléenne", kind: "specification", description: "Opérateurs logiques et tables de vérité utilisés pour construire des conditions.", evidence: ["src:spec-conception", "src:intro-java"]},
    {id: "concept:pseudocode", label: "Pseudocode", kind: "specification", description: "Exprimer l’algorithme indépendamment de Java avec affectation, lecture/écriture et structures de contrôle.", evidence: ["src:spec-conception"]},
    {id: "concept:selection", label: "Sélections", kind: "specification", description: "Sélection simple, alternative et imbriquée au niveau algorithmique.", evidence: ["src:spec-conception", "src:intro-java"]},
    {id: "concept:iteration", label: "Itérations", kind: "specification", description: "Boucles tant que et faire…tant que en pseudocode, puis while/do/for en Java.", evidence: ["src:spec-conception", "src:intro-java"]},
    {id: "concept:input-validation", label: "Validation des entrées", kind: "specification", description: "Valider domaines, bornes et cas invalides avant le traitement.", evidence: ["src:spec-conception", "src:correction-criteria"]},
    {id: "concept:test-design", label: "Jeux d’essais et cas limites", kind: "specification", description: "Concevoir des jeux d’essais incluant cas normaux, limites et hors bornes.", evidence: ["src:spec-conception", "src:correction-criteria"]},
    {id: "concept:main-method", label: "Méthode main", kind: "language", description: "Point d’entrée d’une application Java.", evidence: ["src:intro-java"]},
    {id: "concept:identifiers-comments", label: "Identificateurs et commentaires", kind: "language", description: "Règles de nommage de base, commentaires ligne/bloc et Javadoc.", evidence: ["src:intro-java", "src:style-conventions", "src:correction-criteria"]},
    {id: "concept:primitive-types", label: "Types primitifs Java", kind: "language", description: "Types entiers, flottants, char et boolean avec domaines et littéraux.", evidence: ["src:intro-java"]},
    {id: "concept:variables-initialization", label: "Variables, déclaration et initialisation", kind: "language", description: "Déclaration, affectation, initialisation et compatibilité d’affectation.", evidence: ["src:intro-java"]},
    {id: "concept:constants-java", label: "Constantes Java", kind: "language", description: "Constantes final et conventions de nommage.", evidence: ["src:intro-java", "src:style-conventions"]},
    {id: "concept:arithmetic-operators", label: "Opérateurs arithmétiques", kind: "language", description: "Arithmétique entière/réelle, modulo et priorités.", evidence: ["src:intro-java"]},
    {id: "concept:numeric-conversions", label: "Promotions, conversions implicites et cast", kind: "language", description: "Promotion numérique, compatibilité d’affectation et conversion explicite.", evidence: ["src:intro-java"]},
    {id: "concept:relational-logical-operators", label: "Opérateurs relationnels et logiques", kind: "language", description: "Comparaisons, opérateurs booléens et court-circuit.", evidence: ["src:intro-java"]},
    {id: "concept:string-concatenation", label: "Chaînes et concaténation", kind: "language", description: "Type String introductif et opérateur + de concaténation.", evidence: ["src:intro-java"]},
    {id: "concept:console-io-clavier", label: "Entrées/sorties console et classe Clavier", kind: "language", description: "System.out et méthodes de lecture fournies par la classe Clavier.", evidence: ["src:intro-java"]},
    {id: "concept:if-java", label: "if / else if / else", kind: "language", description: "Sélections Java par conditions booléennes.", evidence: ["src:intro-java"]},
    {id: "concept:switch-java", label: "switch / case", kind: "language", description: "Sélection multiple, case/default et break dans switch.", evidence: ["src:intro-java", "src:correction-criteria"]},
    {id: "concept:while-do-while", label: "while et do…while", kind: "language", description: "Boucles conditionnelles et validation répétée.", evidence: ["src:intro-java"]},
    {id: "concept:for-loop", label: "Boucle for", kind: "language", description: "Boucle for et variable de contrôle.", evidence: ["src:intro-java", "src:correction-criteria"]},
    {id: "concept:execution-trace", label: "Trace d’exécution", kind: "language", description: "Suivre l’évolution des variables et le contrôle pour déterminer un résultat.", evidence: ["src:spec-conception", "src:intro-java", "src:quiz-2016", "src:quiz-history-2018-2019"]},
]
