package inf1120a26

prerequisiteRelationsB: [
    {id: "relation:prereq:classes-objects:access-modifiers", type: "prerequisite", from: "concept:classes-objects", to: "concept:access-modifiers", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:classes-objects:instance-fields", type: "prerequisite", from: "concept:classes-objects", to: "concept:instance-fields", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:instance-fields:getters-setters", type: "prerequisite", from: "concept:instance-fields", to: "concept:getters-setters", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:instance-fields:constructors", type: "prerequisite", from: "concept:instance-fields", to: "concept:constructors", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:constructors:this-keyword", type: "prerequisite", from: "concept:constructors", to: "concept:this-keyword", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:classes-objects:static-members", type: "prerequisite", from: "concept:classes-objects", to: "concept:static-members", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:access-modifiers:encapsulation", type: "prerequisite", from: "concept:access-modifiers", to: "concept:encapsulation", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:getters-setters:encapsulation", type: "prerequisite", from: "concept:getters-setters", to: "concept:encapsulation", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:encapsulation:class-contract-implementation", type: "prerequisite", from: "concept:encapsulation", to: "concept:class-contract-implementation", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:references-null:garbage-collector", type: "prerequisite", from: "concept:references-null", to: "concept:garbage-collector", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:primitive-types:array-declaration-instantiation", type: "prerequisite", from: "concept:primitive-types", to: "concept:array-declaration-instantiation", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:references-null:array-declaration-instantiation", type: "prerequisite", from: "concept:references-null", to: "concept:array-declaration-instantiation", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:array-declaration-instantiation:array-index-length", type: "prerequisite", from: "concept:array-declaration-instantiation", to: "concept:array-index-length", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:for-loop:array-traversal", type: "prerequisite", from: "concept:for-loop", to: "concept:array-traversal", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:array-index-length:array-traversal", type: "prerequisite", from: "concept:array-index-length", to: "concept:array-traversal", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:array-declaration-instantiation:array-copy-reference", type: "prerequisite", from: "concept:array-declaration-instantiation", to: "concept:array-copy-reference", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:method-parameters:arrays-parameters-return", type: "prerequisite", from: "concept:method-parameters", to: "concept:arrays-parameters-return", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:array-declaration-instantiation:arrays-parameters-return", type: "prerequisite", from: "concept:array-declaration-instantiation", to: "concept:arrays-parameters-return", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:classes-objects:object-arrays", type: "prerequisite", from: "concept:classes-objects", to: "concept:object-arrays", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:array-declaration-instantiation:object-arrays", type: "prerequisite", from: "concept:array-declaration-instantiation", to: "concept:object-arrays", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:array-traversal:effective-element-count", type: "prerequisite", from: "concept:array-traversal", to: "concept:effective-element-count", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:array-declaration-instantiation:multidimensional-arrays", type: "prerequisite", from: "concept:array-declaration-instantiation", to: "concept:multidimensional-arrays", basis: "content-dependency", evidence: ["src:arrays"]},
    {id: "relation:prereq:references-null:exception-model", type: "prerequisite", from: "concept:references-null", to: "concept:exception-model", basis: "content-dependency", evidence: ["src:exceptions"]},
    {id: "relation:prereq:array-index-length:exception-model", type: "prerequisite", from: "concept:array-index-length", to: "concept:exception-model", basis: "content-dependency", evidence: ["src:exceptions"]},
    {id: "relation:prereq:string-index-length:exception-model", type: "prerequisite", from: "concept:string-index-length", to: "concept:exception-model", basis: "content-dependency", evidence: ["src:exceptions"]},
    {id: "relation:prereq:exception-model:checked-unchecked", type: "prerequisite", from: "concept:exception-model", to: "concept:checked-unchecked", basis: "content-dependency", evidence: ["src:exceptions"]},
    {id: "relation:prereq:checked-unchecked:try-catch", type: "prerequisite", from: "concept:checked-unchecked", to: "concept:try-catch", basis: "content-dependency", evidence: ["src:exceptions"]},
    {id: "relation:prereq:try-catch:multi-catch", type: "prerequisite", from: "concept:try-catch", to: "concept:multi-catch", basis: "content-dependency", evidence: ["src:exceptions"]},
    {id: "relation:prereq:try-catch:throws-propagation", type: "prerequisite", from: "concept:try-catch", to: "concept:throws-propagation", basis: "content-dependency", evidence: ["src:exceptions"]},
    {id: "relation:prereq:exception-model:custom-exceptions", type: "prerequisite", from: "concept:exception-model", to: "concept:custom-exceptions", basis: "content-dependency", evidence: ["src:exceptions"]},
    {id: "relation:prereq:custom-exceptions:throw-clause", type: "prerequisite", from: "concept:custom-exceptions", to: "concept:throw-clause", basis: "content-dependency", evidence: ["src:exceptions"]},
    {id: "relation:prereq:throw-clause:exception-message", type: "prerequisite", from: "concept:throw-clause", to: "concept:exception-message", basis: "content-dependency", evidence: ["src:exceptions"]},
    {id: "relation:prereq:try-catch:finally", type: "prerequisite", from: "concept:try-catch", to: "concept:finally", basis: "content-dependency", evidence: ["src:exceptions"]},
    {id: "relation:prereq:exception-model:java-io-package", type: "prerequisite", from: "concept:exception-model", to: "concept:java-io-package", basis: "content-dependency", evidence: ["src:text-files"]},
    {id: "relation:prereq:file-paths:file-reading", type: "prerequisite", from: "concept:file-paths", to: "concept:file-reading", basis: "content-dependency", evidence: ["src:text-files"]},
    {id: "relation:prereq:java-io-package:file-reading", type: "prerequisite", from: "concept:java-io-package", to: "concept:file-reading", basis: "content-dependency", evidence: ["src:text-files"]},
    {id: "relation:prereq:java-io-package:file-writing", type: "prerequisite", from: "concept:java-io-package", to: "concept:file-writing", basis: "content-dependency", evidence: ["src:text-files"]},
    {id: "relation:prereq:checked-unchecked:io-exceptions-resources", type: "prerequisite", from: "concept:checked-unchecked", to: "concept:io-exceptions-resources", basis: "content-dependency", evidence: ["src:text-files"]},
    {id: "relation:prereq:file-reading:io-exceptions-resources", type: "prerequisite", from: "concept:file-reading", to: "concept:io-exceptions-resources", basis: "content-dependency", evidence: ["src:text-files"]},
    {id: "relation:prereq:file-writing:io-exceptions-resources", type: "prerequisite", from: "concept:file-writing", to: "concept:io-exceptions-resources", basis: "content-dependency", evidence: ["src:text-files"]},
    {id: "relation:prereq:finally:io-exceptions-resources", type: "prerequisite", from: "concept:finally", to: "concept:io-exceptions-resources", basis: "content-dependency", evidence: ["src:text-files"]},
]
