package inf1120a26

introductionRelationsB: [
    {id: "relation:week07:introduces:string-transform-substring", type: "introduces", from: "week:inf1120-a26:07", to: "concept:string-transform-substring", basis: "explicit", evidence: ["src:moodle-a26", "src:string"]},
    {id: "relation:week07:introduces:string-search-compare", type: "introduces", from: "week:inf1120-a26:07", to: "concept:string-search-compare", basis: "explicit", evidence: ["src:moodle-a26", "src:string"]},
    {id: "relation:week07:introduces:string-static-valueof", type: "introduces", from: "week:inf1120-a26:07", to: "concept:string-static-valueof", basis: "explicit", evidence: ["src:moodle-a26", "src:string"]},
    {id: "relation:week07:introduces:math-static-methods", type: "introduces", from: "week:inf1120-a26:07", to: "concept:math-static-methods", basis: "explicit", evidence: ["src:moodle-a26", "src:math"]},
    {id: "relation:week07:introduces:math-numeric-functions", type: "introduces", from: "week:inf1120-a26:07", to: "concept:math-numeric-functions", basis: "explicit", evidence: ["src:moodle-a26", "src:math"]},
    {id: "relation:week09:introduces:classes-objects", type: "introduces", from: "week:inf1120-a26:09", to: "concept:classes-objects", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week09:introduces:references-null", type: "introduces", from: "week:inf1120-a26:09", to: "concept:references-null", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week09:introduces:access-modifiers", type: "introduces", from: "week:inf1120-a26:09", to: "concept:access-modifiers", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week09:introduces:instance-fields", type: "introduces", from: "week:inf1120-a26:09", to: "concept:instance-fields", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week09:introduces:getters-setters", type: "introduces", from: "week:inf1120-a26:09", to: "concept:getters-setters", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week09:introduces:constructors", type: "introduces", from: "week:inf1120-a26:09", to: "concept:constructors", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week10:introduces:this-keyword", type: "introduces", from: "week:inf1120-a26:10", to: "concept:this-keyword", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week10:introduces:static-members", type: "introduces", from: "week:inf1120-a26:10", to: "concept:static-members", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week10:introduces:encapsulation", type: "introduces", from: "week:inf1120-a26:10", to: "concept:encapsulation", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week10:introduces:class-contract-implementation", type: "introduces", from: "week:inf1120-a26:10", to: "concept:class-contract-implementation", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week10:introduces:garbage-collector", type: "introduces", from: "week:inf1120-a26:10", to: "concept:garbage-collector", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week10:introduces:array-declaration-instantiation", type: "introduces", from: "week:inf1120-a26:10", to: "concept:array-declaration-instantiation", basis: "explicit", evidence: ["src:moodle-a26", "src:arrays"]},
    {id: "relation:week10:introduces:array-index-length", type: "introduces", from: "week:inf1120-a26:10", to: "concept:array-index-length", basis: "explicit", evidence: ["src:moodle-a26", "src:arrays"]},
    {id: "relation:week11:introduces:array-traversal", type: "introduces", from: "week:inf1120-a26:11", to: "concept:array-traversal", basis: "explicit", evidence: ["src:moodle-a26", "src:arrays"]},
    {id: "relation:week11:introduces:array-copy-reference", type: "introduces", from: "week:inf1120-a26:11", to: "concept:array-copy-reference", basis: "explicit", evidence: ["src:moodle-a26", "src:arrays"]},
    {id: "relation:week11:introduces:arrays-parameters-return", type: "introduces", from: "week:inf1120-a26:11", to: "concept:arrays-parameters-return", basis: "explicit", evidence: ["src:moodle-a26", "src:arrays"]},
    {id: "relation:week11:introduces:object-arrays", type: "introduces", from: "week:inf1120-a26:11", to: "concept:object-arrays", basis: "explicit", evidence: ["src:moodle-a26", "src:arrays"]},
    {id: "relation:week11:introduces:effective-element-count", type: "introduces", from: "week:inf1120-a26:11", to: "concept:effective-element-count", basis: "explicit", evidence: ["src:moodle-a26", "src:arrays"]},
    {id: "relation:week11:introduces:multidimensional-arrays", type: "introduces", from: "week:inf1120-a26:11", to: "concept:multidimensional-arrays", basis: "explicit", evidence: ["src:moodle-a26", "src:arrays"]},
    {id: "relation:week12:introduces:exception-model", type: "introduces", from: "week:inf1120-a26:12", to: "concept:exception-model", basis: "explicit", evidence: ["src:moodle-a26", "src:exceptions"]},
    {id: "relation:week12:introduces:checked-unchecked", type: "introduces", from: "week:inf1120-a26:12", to: "concept:checked-unchecked", basis: "explicit", evidence: ["src:moodle-a26", "src:exceptions"]},
    {id: "relation:week12:introduces:try-catch", type: "introduces", from: "week:inf1120-a26:12", to: "concept:try-catch", basis: "explicit", evidence: ["src:moodle-a26", "src:exceptions"]},
    {id: "relation:week12:introduces:multi-catch", type: "introduces", from: "week:inf1120-a26:12", to: "concept:multi-catch", basis: "explicit", evidence: ["src:moodle-a26", "src:exceptions"]},
    {id: "relation:week13:introduces:throws-propagation", type: "introduces", from: "week:inf1120-a26:13", to: "concept:throws-propagation", basis: "explicit", evidence: ["src:moodle-a26", "src:exceptions"]},
    {id: "relation:week13:introduces:custom-exceptions", type: "introduces", from: "week:inf1120-a26:13", to: "concept:custom-exceptions", basis: "explicit", evidence: ["src:moodle-a26", "src:exceptions"]},
    {id: "relation:week13:introduces:throw-clause", type: "introduces", from: "week:inf1120-a26:13", to: "concept:throw-clause", basis: "explicit", evidence: ["src:moodle-a26", "src:exceptions"]},
    {id: "relation:week13:introduces:exception-message", type: "introduces", from: "week:inf1120-a26:13", to: "concept:exception-message", basis: "explicit", evidence: ["src:moodle-a26", "src:exceptions"]},
    {id: "relation:week13:introduces:finally", type: "introduces", from: "week:inf1120-a26:13", to: "concept:finally", basis: "explicit", evidence: ["src:moodle-a26", "src:exceptions"]},
    {id: "relation:week13:introduces:file-paths", type: "introduces", from: "week:inf1120-a26:13", to: "concept:file-paths", basis: "explicit", evidence: ["src:moodle-a26", "src:text-files"]},
    {id: "relation:week13:introduces:java-io-package", type: "introduces", from: "week:inf1120-a26:13", to: "concept:java-io-package", basis: "explicit", evidence: ["src:moodle-a26", "src:text-files"]},
    {id: "relation:week14:introduces:file-reading", type: "introduces", from: "week:inf1120-a26:14", to: "concept:file-reading", basis: "explicit", evidence: ["src:moodle-a26", "src:text-files"]},
    {id: "relation:week14:introduces:file-writing", type: "introduces", from: "week:inf1120-a26:14", to: "concept:file-writing", basis: "explicit", evidence: ["src:moodle-a26", "src:text-files"]},
    {id: "relation:week14:introduces:io-exceptions-resources", type: "introduces", from: "week:inf1120-a26:14", to: "concept:io-exceptions-resources", basis: "explicit", evidence: ["src:moodle-a26", "src:text-files"]},
]
