package inf1120a26

introductionRelationsA: [
    {id: "relation:week01:introduces:program-ipo", type: "introduces", from: "week:inf1120-a26:01", to: "concept:program-ipo", basis: "explicit", evidence: ["src:moodle-a26", "src:introduction"]},
    {id: "relation:week01:introduces:programming-languages", type: "introduces", from: "week:inf1120-a26:01", to: "concept:programming-languages", basis: "explicit", evidence: ["src:moodle-a26", "src:introduction"]},
    {id: "relation:week01:introduces:java-execution-jvm", type: "introduces", from: "week:inf1120-a26:01", to: "concept:java-execution-jvm", basis: "explicit", evidence: ["src:moodle-a26", "src:introduction"]},
    {id: "relation:week01:introduces:software-lifecycle", type: "introduces", from: "week:inf1120-a26:01", to: "concept:software-lifecycle", basis: "explicit", evidence: ["src:moodle-a26", "src:introduction"]},
    {id: "relation:week02:introduces:problem-definition", type: "introduces", from: "week:inf1120-a26:02", to: "concept:problem-definition", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week02:introduces:functional-requirements", type: "introduces", from: "week:inf1120-a26:02", to: "concept:functional-requirements", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week02:introduces:inputs-outputs", type: "introduces", from: "week:inf1120-a26:02", to: "concept:inputs-outputs", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week02:introduces:data-types-model", type: "introduces", from: "week:inf1120-a26:02", to: "concept:data-types-model", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week02:introduces:boolean-logic", type: "introduces", from: "week:inf1120-a26:02", to: "concept:boolean-logic", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week02:introduces:pseudocode", type: "introduces", from: "week:inf1120-a26:02", to: "concept:pseudocode", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week02:introduces:selection", type: "introduces", from: "week:inf1120-a26:02", to: "concept:selection", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week02:introduces:iteration", type: "introduces", from: "week:inf1120-a26:02", to: "concept:iteration", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week02:introduces:input-validation", type: "introduces", from: "week:inf1120-a26:02", to: "concept:input-validation", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week02:introduces:test-design", type: "introduces", from: "week:inf1120-a26:02", to: "concept:test-design", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week03:introduces:main-method", type: "introduces", from: "week:inf1120-a26:03", to: "concept:main-method", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week03:introduces:identifiers-comments", type: "introduces", from: "week:inf1120-a26:03", to: "concept:identifiers-comments", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week03:introduces:primitive-types", type: "introduces", from: "week:inf1120-a26:03", to: "concept:primitive-types", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week03:introduces:variables-initialization", type: "introduces", from: "week:inf1120-a26:03", to: "concept:variables-initialization", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week03:introduces:constants-java", type: "introduces", from: "week:inf1120-a26:03", to: "concept:constants-java", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week03:introduces:arithmetic-operators", type: "introduces", from: "week:inf1120-a26:03", to: "concept:arithmetic-operators", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week03:introduces:numeric-conversions", type: "introduces", from: "week:inf1120-a26:03", to: "concept:numeric-conversions", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week03:introduces:relational-logical-operators", type: "introduces", from: "week:inf1120-a26:03", to: "concept:relational-logical-operators", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week03:introduces:string-concatenation", type: "introduces", from: "week:inf1120-a26:03", to: "concept:string-concatenation", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week03:introduces:console-io-clavier", type: "introduces", from: "week:inf1120-a26:03", to: "concept:console-io-clavier", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week04:introduces:if-java", type: "introduces", from: "week:inf1120-a26:04", to: "concept:if-java", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week04:introduces:switch-java", type: "introduces", from: "week:inf1120-a26:04", to: "concept:switch-java", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week04:introduces:while-do-while", type: "introduces", from: "week:inf1120-a26:04", to: "concept:while-do-while", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week04:introduces:for-loop", type: "introduces", from: "week:inf1120-a26:04", to: "concept:for-loop", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week04:introduces:execution-trace", type: "introduces", from: "week:inf1120-a26:04", to: "concept:execution-trace", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week05:introduces:method-definition-call", type: "introduces", from: "week:inf1120-a26:05", to: "concept:method-definition-call", basis: "explicit", evidence: ["src:moodle-a26", "src:methods"]},
    {id: "relation:week05:introduces:method-parameters", type: "introduces", from: "week:inf1120-a26:05", to: "concept:method-parameters", basis: "explicit", evidence: ["src:moodle-a26", "src:methods"]},
    {id: "relation:week05:introduces:method-return", type: "introduces", from: "week:inf1120-a26:05", to: "concept:method-return", basis: "explicit", evidence: ["src:moodle-a26", "src:methods"]},
    {id: "relation:week06:introduces:pass-by-value", type: "introduces", from: "week:inf1120-a26:06", to: "concept:pass-by-value", basis: "explicit", evidence: ["src:moodle-a26", "src:methods"]},
    {id: "relation:week06:introduces:scope", type: "introduces", from: "week:inf1120-a26:06", to: "concept:scope", basis: "explicit", evidence: ["src:moodle-a26", "src:methods"]},
    {id: "relation:week06:introduces:functional-decomposition", type: "introduces", from: "week:inf1120-a26:06", to: "concept:functional-decomposition", basis: "explicit", evidence: ["src:moodle-a26", "src:methods"]},
    {id: "relation:week06:introduces:method-overloading", type: "introduces", from: "week:inf1120-a26:06", to: "concept:method-overloading", basis: "explicit", evidence: ["src:moodle-a26", "src:methods"]},
    {id: "relation:week07:introduces:string-instance-methods", type: "introduces", from: "week:inf1120-a26:07", to: "concept:string-instance-methods", basis: "explicit", evidence: ["src:moodle-a26", "src:string"]},
    {id: "relation:week07:introduces:string-index-length", type: "introduces", from: "week:inf1120-a26:07", to: "concept:string-index-length", basis: "explicit", evidence: ["src:moodle-a26", "src:string"]},
]
