package inf1120a26

practiceRelations: [
    {id: "relation:week02:practices:problem-definition", type: "practices", from: "week:inf1120-a26:02", to: "concept:problem-definition", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week02:practices:functional-requirements", type: "practices", from: "week:inf1120-a26:02", to: "concept:functional-requirements", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week02:practices:pseudocode", type: "practices", from: "week:inf1120-a26:02", to: "concept:pseudocode", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week03:practices:java-execution-jvm", type: "practices", from: "week:inf1120-a26:03", to: "concept:java-execution-jvm", basis: "explicit", evidence: ["src:moodle-a26", "src:introduction"]},
    {id: "relation:week03:practices:main-method", type: "practices", from: "week:inf1120-a26:03", to: "concept:main-method", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week04:practices:pseudocode", type: "practices", from: "week:inf1120-a26:04", to: "concept:pseudocode", basis: "explicit", evidence: ["src:moodle-a26", "src:spec-conception"]},
    {id: "relation:week04:practices:main-method", type: "practices", from: "week:inf1120-a26:04", to: "concept:main-method", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week04:practices:console-io-clavier", type: "practices", from: "week:inf1120-a26:04", to: "concept:console-io-clavier", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week05:practices:if-java", type: "practices", from: "week:inf1120-a26:05", to: "concept:if-java", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week05:practices:switch-java", type: "practices", from: "week:inf1120-a26:05", to: "concept:switch-java", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week06:practices:while-do-while", type: "practices", from: "week:inf1120-a26:06", to: "concept:while-do-while", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week06:practices:for-loop", type: "practices", from: "week:inf1120-a26:06", to: "concept:for-loop", basis: "explicit", evidence: ["src:moodle-a26", "src:intro-java"]},
    {id: "relation:week07:practices:method-definition-call", type: "practices", from: "week:inf1120-a26:07", to: "concept:method-definition-call", basis: "explicit", evidence: ["src:moodle-a26", "src:methods"]},
    {id: "relation:week07:practices:method-parameters", type: "practices", from: "week:inf1120-a26:07", to: "concept:method-parameters", basis: "explicit", evidence: ["src:moodle-a26", "src:methods"]},
    {id: "relation:week08:practices:method-return", type: "practices", from: "week:inf1120-a26:08", to: "concept:method-return", basis: "explicit", evidence: ["src:moodle-a26", "src:methods"]},
    {id: "relation:week08:practices:functional-decomposition", type: "practices", from: "week:inf1120-a26:08", to: "concept:functional-decomposition", basis: "explicit", evidence: ["src:moodle-a26", "src:methods"]},
    {id: "relation:week09:practices:string-instance-methods", type: "practices", from: "week:inf1120-a26:09", to: "concept:string-instance-methods", basis: "explicit", evidence: ["src:moodle-a26", "src:string"]},
    {id: "relation:week09:practices:string-search-compare", type: "practices", from: "week:inf1120-a26:09", to: "concept:string-search-compare", basis: "explicit", evidence: ["src:moodle-a26", "src:string"]},
    {id: "relation:week10:practices:math-static-methods", type: "practices", from: "week:inf1120-a26:10", to: "concept:math-static-methods", basis: "explicit", evidence: ["src:moodle-a26", "src:math"]},
    {id: "relation:week11:practices:classes-objects", type: "practices", from: "week:inf1120-a26:11", to: "concept:classes-objects", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week11:practices:constructors", type: "practices", from: "week:inf1120-a26:11", to: "concept:constructors", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week11:practices:encapsulation", type: "practices", from: "week:inf1120-a26:11", to: "concept:encapsulation", basis: "explicit", evidence: ["src:moodle-a26", "src:classes-objects"]},
    {id: "relation:week12:practices:array-declaration-instantiation", type: "practices", from: "week:inf1120-a26:12", to: "concept:array-declaration-instantiation", basis: "explicit", evidence: ["src:moodle-a26", "src:arrays"]},
    {id: "relation:week12:practices:array-traversal", type: "practices", from: "week:inf1120-a26:12", to: "concept:array-traversal", basis: "explicit", evidence: ["src:moodle-a26", "src:arrays"]},
    {id: "relation:week13:practices:try-catch", type: "practices", from: "week:inf1120-a26:13", to: "concept:try-catch", basis: "explicit", evidence: ["src:moodle-a26", "src:exceptions"]},
    {id: "relation:week13:practices:checked-unchecked", type: "practices", from: "week:inf1120-a26:13", to: "concept:checked-unchecked", basis: "explicit", evidence: ["src:moodle-a26", "src:exceptions"]},
    {id: "relation:week14:practices:file-reading", type: "practices", from: "week:inf1120-a26:14", to: "concept:file-reading", basis: "explicit", evidence: ["src:moodle-a26", "src:text-files"]},
    {id: "relation:week14:practices:file-writing", type: "practices", from: "week:inf1120-a26:14", to: "concept:file-writing", basis: "explicit", evidence: ["src:moodle-a26", "src:text-files"]},
    {id: "relation:week14:practices:io-exceptions-resources", type: "practices", from: "week:inf1120-a26:14", to: "concept:io-exceptions-resources", basis: "explicit", evidence: ["src:moodle-a26", "src:text-files"]},
]
