package inf1120a26

constraintRelations: [
    {id: "relation:quiz-1:constraint:no-retake", type: "constrained-by", from: "assessment:quiz-1", to: "constraint:quiz-no-retake", basis: "explicit", evidence: ["src:evaluation-agreement-a26"]},
    {id: "relation:quiz-2:constraint:no-retake", type: "constrained-by", from: "assessment:quiz-2", to: "constraint:quiz-no-retake", basis: "explicit", evidence: ["src:evaluation-agreement-a26"]},
    {id: "relation:tp1:constraint:late", type: "constrained-by", from: "assessment:tp1", to: "constraint:tp1-tp2-late", basis: "explicit", evidence: ["src:evaluation-agreement-a26"]},
    {id: "relation:tp2:constraint:late", type: "constrained-by", from: "assessment:tp2", to: "constraint:tp1-tp2-late", basis: "explicit", evidence: ["src:evaluation-agreement-a26"]},
    {id: "relation:tp3:constraint:no-late", type: "constrained-by", from: "assessment:tp3", to: "constraint:tp3-no-late", basis: "explicit", evidence: ["src:evaluation-agreement-a26"]},
    {id: "relation:intra:constraint:exam-note-sheet", type: "constrained-by", from: "assessment:intra", to: "constraint:exam-note-sheet", basis: "explicit", evidence: ["src:exam-directives"]},
    {id: "relation:intra:constraint:exam-no-electronics", type: "constrained-by", from: "assessment:intra", to: "constraint:exam-no-electronics", basis: "explicit", evidence: ["src:exam-directives"]},
    {id: "relation:intra:constraint:exam-student-card", type: "constrained-by", from: "assessment:intra", to: "constraint:exam-student-card", basis: "explicit", evidence: ["src:exam-directives"]},
    {id: "relation:intra:constraint:exam-exit-terminal", type: "constrained-by", from: "assessment:intra", to: "constraint:exam-exit-terminal", basis: "explicit", evidence: ["src:exam-directives"]},
    {id: "relation:intra:constraint:exam-three-hours", type: "constrained-by", from: "assessment:intra", to: "constraint:exam-three-hours", basis: "explicit", evidence: ["src:exam-directives"]},
    {id: "relation:final:constraint:exam-note-sheet", type: "constrained-by", from: "assessment:final", to: "constraint:exam-note-sheet", basis: "explicit", evidence: ["src:exam-directives"]},
    {id: "relation:final:constraint:exam-no-electronics", type: "constrained-by", from: "assessment:final", to: "constraint:exam-no-electronics", basis: "explicit", evidence: ["src:exam-directives"]},
    {id: "relation:final:constraint:exam-student-card", type: "constrained-by", from: "assessment:final", to: "constraint:exam-student-card", basis: "explicit", evidence: ["src:exam-directives"]},
    {id: "relation:final:constraint:exam-exit-terminal", type: "constrained-by", from: "assessment:final", to: "constraint:exam-exit-terminal", basis: "explicit", evidence: ["src:exam-directives"]},
    {id: "relation:final:constraint:exam-three-hours", type: "constrained-by", from: "assessment:final", to: "constraint:exam-three-hours", basis: "explicit", evidence: ["src:exam-directives"]},
    {id: "relation:identifiers-comments:constraint:meaningful-names", type: "constrained-by", from: "concept:identifiers-comments", to: "constraint:meaningful-names", basis: "explicit", evidence: ["src:style-conventions", "src:correction-criteria"]},
    {id: "relation:identifiers-comments:constraint:javadoc-file", type: "constrained-by", from: "concept:identifiers-comments", to: "constraint:javadoc-file", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:identifiers-comments:constraint:javadoc-method", type: "constrained-by", from: "concept:identifiers-comments", to: "constraint:javadoc-method", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:identifiers-comments:constraint:indentation-braces", type: "constrained-by", from: "concept:identifiers-comments", to: "constraint:indentation-braces", basis: "explicit", evidence: ["src:style-conventions", "src:correction-criteria"]},
    {id: "relation:identifiers-comments:constraint:line-length-120", type: "constrained-by", from: "concept:identifiers-comments", to: "constraint:line-length-120", basis: "explicit", evidence: ["src:style-conventions", "src:correction-criteria"]},
    {id: "relation:variables-initialization:constraint:declarations-at-start", type: "constrained-by", from: "concept:variables-initialization", to: "constraint:declarations-at-start", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:variables-initialization:constraint:one-declaration-instruction-line", type: "constrained-by", from: "concept:variables-initialization", to: "constraint:one-declaration-instruction-line", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:method-definition-call:constraint:javadoc-method", type: "constrained-by", from: "concept:method-definition-call", to: "constraint:javadoc-method", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:method-definition-call:constraint:declarations-at-start", type: "constrained-by", from: "concept:method-definition-call", to: "constraint:declarations-at-start", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:method-return:constraint:single-return", type: "constrained-by", from: "concept:method-return", to: "constraint:single-return", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:method-return:constraint:return-not-in-control", type: "constrained-by", from: "concept:method-return", to: "constraint:return-not-in-control", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:for-loop:constraint:for-control-discipline", type: "constrained-by", from: "concept:for-loop", to: "constraint:for-control-discipline", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:for-loop:constraint:no-continue", type: "constrained-by", from: "concept:for-loop", to: "constraint:no-continue", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:while-do-while:constraint:no-while-true", type: "constrained-by", from: "concept:while-do-while", to: "constraint:no-while-true", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:while-do-while:constraint:no-continue", type: "constrained-by", from: "concept:while-do-while", to: "constraint:no-continue", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:switch-java:constraint:break-switch-only", type: "constrained-by", from: "concept:switch-java", to: "constraint:break-switch-only", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:functional-decomposition:constraint:no-globals", type: "constrained-by", from: "concept:functional-decomposition", to: "constraint:no-globals", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:functional-decomposition:constraint:low-coupling-high-cohesion", type: "constrained-by", from: "concept:functional-decomposition", to: "constraint:low-coupling-high-cohesion", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:functional-decomposition:constraint:short-robust-methods", type: "constrained-by", from: "concept:functional-decomposition", to: "constraint:short-robust-methods", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:encapsulation:constraint:low-coupling-high-cohesion", type: "constrained-by", from: "concept:encapsulation", to: "constraint:low-coupling-high-cohesion", basis: "explicit", evidence: ["src:correction-criteria"]},
    {id: "relation:input-validation:constraint:validate-inputs", type: "constrained-by", from: "concept:input-validation", to: "constraint:validate-inputs", basis: "explicit", evidence: ["src:correction-criteria"]},
]
