package inf1120a26

prerequisiteRelationsA: [
    {id: "relation:prereq:software-lifecycle:problem-definition", type: "prerequisite", from: "concept:software-lifecycle", to: "concept:problem-definition", basis: "content-dependency", evidence: ["src:spec-conception"]},
    {id: "relation:prereq:problem-definition:functional-requirements", type: "prerequisite", from: "concept:problem-definition", to: "concept:functional-requirements", basis: "content-dependency", evidence: ["src:spec-conception"]},
    {id: "relation:prereq:functional-requirements:inputs-outputs", type: "prerequisite", from: "concept:functional-requirements", to: "concept:inputs-outputs", basis: "content-dependency", evidence: ["src:spec-conception"]},
    {id: "relation:prereq:inputs-outputs:data-types-model", type: "prerequisite", from: "concept:inputs-outputs", to: "concept:data-types-model", basis: "content-dependency", evidence: ["src:spec-conception"]},
    {id: "relation:prereq:data-types-model:pseudocode", type: "prerequisite", from: "concept:data-types-model", to: "concept:pseudocode", basis: "content-dependency", evidence: ["src:spec-conception"]},
    {id: "relation:prereq:boolean-logic:selection", type: "prerequisite", from: "concept:boolean-logic", to: "concept:selection", basis: "content-dependency", evidence: ["src:spec-conception"]},
    {id: "relation:prereq:selection:iteration", type: "prerequisite", from: "concept:selection", to: "concept:iteration", basis: "content-dependency", evidence: ["src:spec-conception"]},
    {id: "relation:prereq:pseudocode:input-validation", type: "prerequisite", from: "concept:pseudocode", to: "concept:input-validation", basis: "content-dependency", evidence: ["src:spec-conception"]},
    {id: "relation:prereq:input-validation:test-design", type: "prerequisite", from: "concept:input-validation", to: "concept:test-design", basis: "content-dependency", evidence: ["src:spec-conception"]},
    {id: "relation:prereq:java-execution-jvm:main-method", type: "prerequisite", from: "concept:java-execution-jvm", to: "concept:main-method", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:data-types-model:primitive-types", type: "prerequisite", from: "concept:data-types-model", to: "concept:primitive-types", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:primitive-types:variables-initialization", type: "prerequisite", from: "concept:primitive-types", to: "concept:variables-initialization", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:variables-initialization:constants-java", type: "prerequisite", from: "concept:variables-initialization", to: "concept:constants-java", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:primitive-types:arithmetic-operators", type: "prerequisite", from: "concept:primitive-types", to: "concept:arithmetic-operators", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:arithmetic-operators:numeric-conversions", type: "prerequisite", from: "concept:arithmetic-operators", to: "concept:numeric-conversions", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:boolean-logic:relational-logical-operators", type: "prerequisite", from: "concept:boolean-logic", to: "concept:relational-logical-operators", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:variables-initialization:string-concatenation", type: "prerequisite", from: "concept:variables-initialization", to: "concept:string-concatenation", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:main-method:console-io-clavier", type: "prerequisite", from: "concept:main-method", to: "concept:console-io-clavier", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:relational-logical-operators:if-java", type: "prerequisite", from: "concept:relational-logical-operators", to: "concept:if-java", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:if-java:switch-java", type: "prerequisite", from: "concept:if-java", to: "concept:switch-java", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:if-java:while-do-while", type: "prerequisite", from: "concept:if-java", to: "concept:while-do-while", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:while-do-while:for-loop", type: "prerequisite", from: "concept:while-do-while", to: "concept:for-loop", basis: "content-dependency", evidence: ["src:intro-java"]},
    {id: "relation:prereq:if-java:execution-trace", type: "prerequisite", from: "concept:if-java", to: "concept:execution-trace", basis: "content-dependency", evidence: ["src:spec-conception"]},
    {id: "relation:prereq:for-loop:execution-trace", type: "prerequisite", from: "concept:for-loop", to: "concept:execution-trace", basis: "content-dependency", evidence: ["src:spec-conception"]},
    {id: "relation:prereq:main-method:method-definition-call", type: "prerequisite", from: "concept:main-method", to: "concept:method-definition-call", basis: "content-dependency", evidence: ["src:methods"]},
    {id: "relation:prereq:variables-initialization:method-parameters", type: "prerequisite", from: "concept:variables-initialization", to: "concept:method-parameters", basis: "content-dependency", evidence: ["src:methods"]},
    {id: "relation:prereq:method-definition-call:method-parameters", type: "prerequisite", from: "concept:method-definition-call", to: "concept:method-parameters", basis: "content-dependency", evidence: ["src:methods"]},
    {id: "relation:prereq:method-parameters:method-return", type: "prerequisite", from: "concept:method-parameters", to: "concept:method-return", basis: "content-dependency", evidence: ["src:methods"]},
    {id: "relation:prereq:method-parameters:pass-by-value", type: "prerequisite", from: "concept:method-parameters", to: "concept:pass-by-value", basis: "content-dependency", evidence: ["src:methods"]},
    {id: "relation:prereq:method-definition-call:scope", type: "prerequisite", from: "concept:method-definition-call", to: "concept:scope", basis: "content-dependency", evidence: ["src:methods"]},
    {id: "relation:prereq:method-definition-call:functional-decomposition", type: "prerequisite", from: "concept:method-definition-call", to: "concept:functional-decomposition", basis: "content-dependency", evidence: ["src:methods"]},
    {id: "relation:prereq:method-definition-call:method-overloading", type: "prerequisite", from: "concept:method-definition-call", to: "concept:method-overloading", basis: "content-dependency", evidence: ["src:methods"]},
    {id: "relation:prereq:string-concatenation:string-instance-methods", type: "prerequisite", from: "concept:string-concatenation", to: "concept:string-instance-methods", basis: "content-dependency", evidence: ["src:string"]},
    {id: "relation:prereq:string-instance-methods:string-index-length", type: "prerequisite", from: "concept:string-instance-methods", to: "concept:string-index-length", basis: "content-dependency", evidence: ["src:string"]},
    {id: "relation:prereq:string-index-length:string-transform-substring", type: "prerequisite", from: "concept:string-index-length", to: "concept:string-transform-substring", basis: "content-dependency", evidence: ["src:string"]},
    {id: "relation:prereq:string-transform-substring:string-search-compare", type: "prerequisite", from: "concept:string-transform-substring", to: "concept:string-search-compare", basis: "content-dependency", evidence: ["src:string"]},
    {id: "relation:prereq:string-instance-methods:string-static-valueof", type: "prerequisite", from: "concept:string-instance-methods", to: "concept:string-static-valueof", basis: "content-dependency", evidence: ["src:string"]},
    {id: "relation:prereq:method-definition-call:math-static-methods", type: "prerequisite", from: "concept:method-definition-call", to: "concept:math-static-methods", basis: "content-dependency", evidence: ["src:math"]},
    {id: "relation:prereq:math-static-methods:math-numeric-functions", type: "prerequisite", from: "concept:math-static-methods", to: "concept:math-numeric-functions", basis: "content-dependency", evidence: ["src:math"]},
    {id: "relation:prereq:method-definition-call:classes-objects", type: "prerequisite", from: "concept:method-definition-call", to: "concept:classes-objects", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:variables-initialization:references-null", type: "prerequisite", from: "concept:variables-initialization", to: "concept:references-null", basis: "content-dependency", evidence: ["src:classes-objects"]},
    {id: "relation:prereq:classes-objects:references-null", type: "prerequisite", from: "concept:classes-objects", to: "concept:references-null", basis: "content-dependency", evidence: ["src:classes-objects"]},
]
