package inf1035a26

concepts: [
    {id: "concept:physical-machine", label: "Physical machine", kind: "hardware", description: "CPU, RAM, storage and input/output as distinct machine roles.", evidence: ["src:chapter-01"]},
    {id: "concept:cpu", label: "CPU", kind: "hardware", description: "Processor executing machine instructions.", evidence: ["src:chapter-01"]},
    {id: "concept:ram", label: "RAM", kind: "hardware", description: "Working memory used during execution.", evidence: ["src:chapter-01"]},
    {id: "concept:storage", label: "Storage", kind: "hardware", description: "Persistent data/program storage distinct from RAM.", evidence: ["src:chapter-01"]},
    {id: "concept:io-devices", label: "Input/output", kind: "hardware", description: "Machine interaction through input and output devices.", evidence: ["src:chapter-01"]},
    {id: "concept:binary-representation", label: "Binary representation", kind: "representation", description: "Information represented with bits and positional binary values.", evidence: ["src:chapter-01"]},
    {id: "concept:bit", label: "Bit", kind: "representation", description: "Binary digit used as the elementary representation unit.", evidence: ["src:chapter-01"]},
    {id: "concept:byte", label: "Byte", kind: "representation", description: "Eight bits form one byte.", evidence: ["src:chapter-01"]},
    {id: "concept:typed-interpretation", label: "Bits require type/encoding interpretation", kind: "representation", description: "Bit patterns do not carry intrinsic meaning; interpretation determines their value.", evidence: ["src:chapter-01"]},
    {id: "concept:ascii", label: "ASCII", kind: "encoding", description: "Character encoding foundation introduced in Chapter 1.", evidence: ["src:chapter-01"]},
    {id: "concept:unicode", label: "Unicode", kind: "encoding", description: "Character repertoire/encoding model introduced with text representation.", evidence: ["src:chapter-01"]},
    {id: "concept:utf8", label: "UTF-8", kind: "encoding", description: "Unicode encoding used for variable-length byte representation.", evidence: ["src:chapter-01"]},
    {id: "concept:twos-complement", label: "Two's complement", kind: "representation", description: "Signed integer representation introduced in Chapter 1.", evidence: ["src:chapter-01"]},
    {id: "concept:floating-point", label: "Floating-point representation", kind: "representation", description: "Simplified model for representing non-integer numerical values.", evidence: ["src:chapter-01"]},
    {id: "concept:execution-model", label: "Execution model", kind: "execution", description: "Machine-language execution through fetch, decode and execute.", evidence: ["src:chapter-01"]},
    {id: "concept:machine-language", label: "Machine language", kind: "execution", description: "Low-level instructions directly executable by the processor.", evidence: ["src:chapter-01"]},
    {id: "concept:fetch-decode-execute", label: "Fetch → decode → execute", kind: "execution", description: "Simplified processor instruction cycle.", evidence: ["src:chapter-01"]},
    {id: "concept:programming-abstraction", label: "Programming abstraction", kind: "language", description: "Progression from low-level to high-level programming languages.", evidence: ["src:chapter-01"]},
    {id: "concept:compiler", label: "Compiler", kind: "language", description: "Translation model contrasted with interpretation.", evidence: ["src:chapter-01"]},
    {id: "concept:interpreter", label: "Interpreter", kind: "language", description: "Execution model used to explain Python's programming environment.", evidence: ["src:chapter-01"]},
    {id: "concept:python-environment", label: "Python execution environment", kind: "environment", description: "Python used interactively, as scripts and through Jupyter.", evidence: ["src:chapter-01"]},
    {id: "concept:interactive-mode", label: "Interactive mode", kind: "environment", description: "Immediate Python command execution.", evidence: ["src:chapter-01"]},
    {id: "concept:script-mode", label: "Script mode", kind: "environment", description: "Python program execution from source files.", evidence: ["src:chapter-01"]},
    {id: "concept:jupyter", label: "Jupyter", kind: "environment", description: "Notebook execution environment introduced in Chapter 1.", evidence: ["src:chapter-01"]},
    {id: "concept:syntax-vocabulary", label: "Syntax, keywords, operators and statements", kind: "language", description: "Core vocabulary for describing Python program structure.", evidence: ["src:chapter-01"]},
    {id: "concept:variables", label: "Variables", kind: "language", description: "Python variables as scheduled for September 15.", evidence: ["src:calendar-a26"]},
    {id: "concept:operators", label: "Operators", kind: "language", description: "Python operators as scheduled for September 15.", evidence: ["src:calendar-a26"]},
    {id: "concept:output", label: "Affichage", kind: "io", description: "Program output as scheduled for September 15.", evidence: ["src:calendar-a26"]},
    {id: "concept:conditions", label: "Conditions", kind: "control-flow", description: "Conditional execution.", evidence: ["src:calendar-a26"]},
    {id: "concept:boolean-logic", label: "Logique booléenne", kind: "control-flow", description: "Boolean reasoning used by conditional and iterative control flow.", evidence: ["src:calendar-a26"]},
    {id: "concept:loops", label: "Boucles", kind: "control-flow", description: "Iterative control flow.", evidence: ["src:calendar-a26"]},
    {id: "concept:functions", label: "Fonctions", kind: "function", description: "Function definition/call abstraction.", evidence: ["src:calendar-a26"]},
    {id: "concept:files", label: "Fichiers", kind: "io", description: "File input/output.", evidence: ["src:calendar-a26"]},
    {id: "concept:exceptions", label: "Exceptions", kind: "exception", description: "Exception-based error handling.", evidence: ["src:calendar-a26"]},
    {id: "concept:lists", label: "Listes", kind: "collection", description: "Ordered mutable collection topic.", evidence: ["src:calendar-a26"]},
    {id: "concept:tuples", label: "Tuples", kind: "collection", description: "Tuple collection topic.", evidence: ["src:calendar-a26"]},
    {id: "concept:strings", label: "Strings", kind: "structured-data", description: "String handling preceding CSV work.", evidence: ["src:calendar-a26"]},
    {id: "concept:csv", label: "CSV", kind: "structured-data", description: "Delimited tabular text data.", evidence: ["src:calendar-a26"]},
    {id: "concept:dictionaries", label: "Dictionnaires", kind: "collection", description: "Key/value collection topic.", evidence: ["src:calendar-a26"]},
    {id: "concept:sets", label: "Ensembles", kind: "collection", description: "Set collection topic.", evidence: ["src:calendar-a26"]},
    {id: "concept:json", label: "JSON", kind: "structured-data", description: "Structured serialized data representation.", evidence: ["src:calendar-a26"]},
    {id: "concept:numpy", label: "NumPy", kind: "numerical-computing", description: "Scientific/numerical Python tooling scheduled after structured data.", evidence: ["src:calendar-a26"]},
    {id: "concept:pandas", label: "Pandas", kind: "tabular-data", description: "Tabular/data-analysis tooling.", evidence: ["src:calendar-a26"]},
    {id: "concept:matplotlib", label: "Matplotlib", kind: "visualization", description: "Data visualization tooling.", evidence: ["src:calendar-a26"]},
    {id: "concept:scikit-learn", label: "scikit-learn", kind: "machine-learning", description: "Machine-learning tooling at the end of the scheduled progression.", evidence: ["src:calendar-a26"]},
]
