package inf1035a26

relations: [
    {id: "relation:layer-machine-binary", type: "precedes", from: "concept:physical-machine", to: "concept:binary-representation", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:layer-binary-execution", type: "precedes", from: "concept:binary-representation", to: "concept:execution-model", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:layer-execution-abstraction", type: "precedes", from: "concept:execution-model", to: "concept:programming-abstraction", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:layer-abstraction-python", type: "precedes", from: "concept:programming-abstraction", to: "concept:python-environment", basis: "content-dependency", evidence: ["src:chapter-01"]},

    {id: "relation:byte-bit", type: "depends-on", from: "concept:byte", to: "concept:bit", basis: "explicit", evidence: ["src:chapter-01"], note: "8 bits = 1 byte"},
    {id: "relation:typed-binary", type: "depends-on", from: "concept:typed-interpretation", to: "concept:binary-representation", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:ascii-binary", type: "depends-on", from: "concept:ascii", to: "concept:binary-representation", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:unicode-binary", type: "depends-on", from: "concept:unicode", to: "concept:binary-representation", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:utf8-unicode", type: "depends-on", from: "concept:utf8", to: "concept:unicode", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:twos-binary", type: "depends-on", from: "concept:twos-complement", to: "concept:binary-representation", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:float-binary", type: "depends-on", from: "concept:floating-point", to: "concept:binary-representation", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:fetch-machine-language", type: "depends-on", from: "concept:fetch-decode-execute", to: "concept:machine-language", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:fetch-cpu", type: "depends-on", from: "concept:fetch-decode-execute", to: "concept:cpu", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:python-interpreter", type: "depends-on", from: "concept:python-environment", to: "concept:interpreter", basis: "content-dependency", evidence: ["src:chapter-01"]},
    {id: "relation:interactive-python", type: "extends", from: "concept:interactive-mode", to: "concept:python-environment", basis: "explicit", evidence: ["src:chapter-01"]},
    {id: "relation:script-python", type: "extends", from: "concept:script-mode", to: "concept:python-environment", basis: "explicit", evidence: ["src:chapter-01"]},
    {id: "relation:jupyter-python", type: "extends", from: "concept:jupyter", to: "concept:python-environment", basis: "explicit", evidence: ["src:chapter-01"]},
    {id: "relation:typed-p9", type: "evidenced-by", from: "concept:typed-interpretation", to: "material:chapter01-p9", basis: "explicit", evidence: ["src:chapter-01"]},
    {id: "relation:chapter-synthesis", type: "evidenced-by", from: "concept:binary-representation", to: "material:chapter01-p18-20", basis: "explicit", evidence: ["src:chapter-01"], note: "Pages 18–20 provide the compact synthesis/glossary."},

    {id: "relation:variables-conditions", type: "precedes", from: "concept:variables", to: "concept:conditions", basis: "schedule-sequence", evidence: ["src:calendar-a26"]},
    {id: "relation:conditions-boolean", type: "depends-on", from: "concept:conditions", to: "concept:boolean-logic", basis: "content-dependency", evidence: ["src:calendar-a26"]},
    {id: "relation:conditions-loops", type: "precedes", from: "concept:conditions", to: "concept:loops", basis: "schedule-sequence", evidence: ["src:calendar-a26"]},
    {id: "relation:loops-boolean", type: "depends-on", from: "concept:loops", to: "concept:boolean-logic", basis: "content-dependency", evidence: ["src:calendar-a26"]},
    {id: "relation:loops-functions", type: "precedes", from: "concept:loops", to: "concept:functions", basis: "schedule-sequence", evidence: ["src:calendar-a26"]},
    {id: "relation:csv-files", type: "depends-on", from: "concept:csv", to: "concept:files", basis: "content-dependency", evidence: ["src:calendar-a26"]},
    {id: "relation:csv-strings", type: "depends-on", from: "concept:csv", to: "concept:strings", basis: "content-dependency", evidence: ["src:calendar-a26"]},
    {id: "relation:json-collections", type: "depends-on", from: "concept:json", to: "concept:dictionaries", basis: "content-dependency", evidence: ["src:calendar-a26"]},
    {id: "relation:numpy-typed", type: "depends-on", from: "concept:numpy", to: "concept:typed-interpretation", basis: "content-dependency", evidence: ["src:chapter-01", "src:calendar-a26"], note: "Representation/type interpretation is a conceptual precursor to later numerical data tooling."},
    {id: "relation:pandas-numpy", type: "precedes", from: "concept:numpy", to: "concept:pandas", basis: "schedule-sequence", evidence: ["src:calendar-a26"]},
    {id: "relation:pandas-matplotlib", type: "precedes", from: "concept:pandas", to: "concept:matplotlib", basis: "schedule-sequence", evidence: ["src:calendar-a26"]},
    {id: "relation:matplotlib-sklearn", type: "precedes", from: "concept:matplotlib", to: "concept:scikit-learn", basis: "schedule-sequence", evidence: ["src:calendar-a26"]},

    {id: "relation:w01-machine", type: "introduces", from: "week:01", to: "concept:physical-machine", basis: "explicit", evidence: ["src:calendar-a26", "src:chapter-01"]},
    {id: "relation:w01-binary", type: "introduces", from: "week:01", to: "concept:binary-representation", basis: "explicit", evidence: ["src:calendar-a26", "src:chapter-01"]},
    {id: "relation:w01-execution", type: "introduces", from: "week:01", to: "concept:execution-model", basis: "explicit", evidence: ["src:calendar-a26", "src:chapter-01"]},
    {id: "relation:w01-abstraction", type: "introduces", from: "week:01", to: "concept:programming-abstraction", basis: "explicit", evidence: ["src:calendar-a26", "src:chapter-01"]},
    {id: "relation:w01-python", type: "introduces", from: "week:01", to: "concept:python-environment", basis: "explicit", evidence: ["src:calendar-a26", "src:chapter-01"]},
    {id: "relation:w02-variables", type: "introduces", from: "week:02", to: "concept:variables", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w02-operators", type: "introduces", from: "week:02", to: "concept:operators", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w03-conditions", type: "introduces", from: "week:03", to: "concept:conditions", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w03-boolean", type: "introduces", from: "week:03", to: "concept:boolean-logic", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w04-loops", type: "introduces", from: "week:04", to: "concept:loops", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w05-functions", type: "introduces", from: "week:05", to: "concept:functions", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w06-files", type: "introduces", from: "week:06", to: "concept:files", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w06-exceptions", type: "introduces", from: "week:06", to: "concept:exceptions", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w07-lists", type: "introduces", from: "week:07", to: "concept:lists", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w07-tuples", type: "introduces", from: "week:07", to: "concept:tuples", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w09-strings", type: "introduces", from: "week:09", to: "concept:strings", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w09-csv", type: "introduces", from: "week:09", to: "concept:csv", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w10-dicts", type: "introduces", from: "week:10", to: "concept:dictionaries", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w10-sets", type: "introduces", from: "week:10", to: "concept:sets", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w10-json", type: "introduces", from: "week:10", to: "concept:json", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w11-numpy", type: "introduces", from: "week:11", to: "concept:numpy", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w12-pandas", type: "introduces", from: "week:12", to: "concept:pandas", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w13-matplotlib", type: "introduces", from: "week:13", to: "concept:matplotlib", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w14-sklearn", type: "introduces", from: "week:14", to: "concept:scikit-learn", basis: "explicit", evidence: ["src:calendar-a26"]},

    {id: "relation:w04-release-tp1", type: "releases", from: "week:04", to: "assessment:tp1", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w07-due-tp1", type: "due-at", from: "assessment:tp1", to: "week:07", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w09-release-tp2", type: "releases", from: "week:09", to: "assessment:tp2", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w12-due-tp2", type: "due-at", from: "assessment:tp2", to: "week:12", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w13-release-tp3", type: "releases", from: "week:13", to: "assessment:tp3", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w16-due-tp3", type: "due-at", from: "assessment:tp3", to: "week:16", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:w08-midterm", type: "assesses", from: "week:08", to: "assessment:midterm", basis: "explicit", evidence: ["src:calendar-a26"], note: "Calendar states Ch. 1–7."},
    {id: "relation:w16-final", type: "assesses", from: "week:16", to: "assessment:final", basis: "explicit", evidence: ["src:calendar-a26"], note: "Calendar states entire course."},
    {id: "relation:final-course-scope", type: "assesses", from: "assessment:final", to: "uqam:course:inf1035-a26", basis: "explicit", evidence: ["src:calendar-a26"], note: "Final scope is the entire course."},

    {id: "relation:course-exam-gate", type: "constrained-by", from: "uqam:course:inf1035-a26", to: "constraint:exam-combined-minimum", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:course-overall-gate", type: "constrained-by", from: "uqam:course:inf1035-a26", to: "constraint:overall-minimum", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:course-no-break", type: "constrained-by", from: "uqam:course:inf1035-a26", to: "constraint:no-science-reading-week", basis: "explicit", evidence: ["src:calendar-a26"]},
    {id: "relation:course-withdrawal", type: "constrained-by", from: "uqam:course:inf1035-a26", to: "constraint:withdrawal-without-failure", basis: "explicit", evidence: ["src:calendar-a26"]},
]
